apiVersion: v1
stringData:
  COUNT: "5"
  WAIT: "5"
  perulo: "Este es el invierno de nuestro descontento"
  text.txt: "Convertido en verano por este sol de York"
kind: Secret
metadata:
  name: espera
  namespace: secretos
type: Opaque
